import { StyleSheet, Platform } from "react-native";

export const currentTabStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#f5f5f5",
  },
  listContainer: {
    padding: 16,
  },
  card: {
    backgroundColor: "white",
    borderRadius: 16,
    marginBottom: 8,
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    overflow: "hidden",
    position: "relative",
    padding: 16,
  },
  cardWithVariations: {
    borderBottomLeftRadius: 75,
    borderBottomRightRadius: 75,
  },
  editButton: {
    position: "absolute",
    top: 4,
    right: 4,
    margin: 12,
    zIndex: 1,
    backgroundColor: "rgba(255, 255, 255, 0.9)",
    padding: 12,
    borderRadius: 18,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.6,
    shadowRadius: 2,
    elevation: 5,
  },
  showVariationsButton: {
    position: "absolute",
    top: 64,
    right: 4,
    margin: 12,
    zIndex: 1,
    backgroundColor: "rgba(255, 255, 255, 0.6)",
    padding: 12,
    borderRadius: 18,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.6,
    shadowRadius: 2,
    elevation: 5,
  },
  topContainer: {
    flexDirection: "row",
    gap: 16,
  },
  detailsContainer: {
    flexDirection: "row",
    justifyContent: "flex-start",
    gap: 0,
  },
  materialImage: {
    width: 120,
    height: 120,
    borderRadius: 8,
    resizeMode: "cover",
  },
  mainInfoContainer: {
    flex: 0.9,
    justifyContent: "space-between",
  },
  materialName: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#000",
    marginBottom: 4,
  },
  description: {
    fontSize: 14,
    color: "#666",
    marginBottom: 4,
    flex: 1,
  },
  variationsTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: "#333",
    alignSelf: "flex-start",
  },
  variationsContainer: {
    marginTop: 16,
    // backgroundColor: 'pink',
  },
  variationsContentContainer: {
    justifyContent: "space-evenly",
    gap: 10,
    flexDirection: "row",
    flexWrap: "wrap",
  },
  variationItem: {
    backgroundColor: "#f8f8f8",
    color: "black",
    paddingVertical: 2,
    paddingHorizontal: 2,
    marginBottom: 4,
    borderRadius: 36,
    ...Platform.select({
      ios: {
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.2,
        shadowRadius: 2,
      },
      android: {
        elevation: 2,
      },
    }),
  },
  variationImage: {
    width: 65,
    height: 65,
    borderRadius: 33,
  },
  variationText: {
    flex: 1,
    fontSize: 13,
    color: "#444",
  },
  cardContent: {
    flex: 1,
    padding: 12,
  },
  addButton: {
    position: "absolute",
    bottom: 20,
    right: 20,
    backgroundColor: "white",
    borderRadius: 25,
    elevation: 5,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
  },
});
